version: "3.7"

services:
  app:
    build:
      context: .
    env_file:
      - .env
    restart: on-failure
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: >
      npm run watch:server
  db:
    image: postgres:14.2-alpine
    ports:
      - "5433:5432"
    env_file:
      - .env.-db
    restart: on-failure
    volumes:
      - ./postgres:/var/lib/postgresql
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
